### ISSUE TITLE
Question on updating

### ISSUE THREAD

**Issue by mattbk** [jemus42/mastodon-instance-stats#2]
It looks like the API has changed, so `time` and `date` need to be parsed out. Should these be created from `updated_at` or `checked_at`?

**Comment by jemus42** [comment]
Uhm, good question. I haven't touched this code since august of last year, and quite frankly, I have no idea. I recommend checking with instances.social: https://github.com/thekinrar/mastodon-instances

**Comment by mattbk** [comment]
Thanks. I think I can make it work. Are you accepting PRs toward this repo, or should I run off with a fork?

**Comment by jemus42** [comment]
You might as well run off with a fork, as I don't plan on reviving this repo in the near future, especially since I feel like https://fediverse.network/ already covers most of what I'm interested in.

**Comment by mattbk** [comment]
Great, thanks.
